import { createFileRoute, Link } from "@tanstack/react-router";
import { BadgeIndianRupee, MapPin, ShieldCheck, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title:"About Udaya Ventures — Direct Property Sales"},{ name:"description",content:"Learn about Udaya Ventures' direct, transparent approach to helping Indian families find quality properties."},{ property:"og:title",content:"About Udaya Ventures"},{ property:"og:description",content:"Quality properties, transparent prices and direct expert assistance."},{ property:"og:type",content:"website"},{ name:"twitter:card",content:"summary_large_image"}] }), component: About });
function About(){ return <>
  <section className="container-site grid gap-10 py-14 md:grid-cols-2 md:items-center md:py-20">
    <div><p className="eyebrow">About us</p><h1 className="mt-2 text-5xl font-semibold md:text-6xl">Homes selected for real life.</h1><p className="mt-6 text-lg text-muted-foreground">Udaya Ventures is a direct property sales company helping families discover quality apartments, villas, independent homes and residential plots in India's growing cities.</p><p className="mt-4 text-muted-foreground">Our approach is deliberately simple: clear property information, visible starting prices and one expert team to guide you from first enquiry to site visit.</p><Button asChild variant="brass" size="xl" className="mt-8"><Link to="/properties">Explore Properties</Link></Button></div>
    <img src="/images/interior-1.jpg" alt="Thoughtfully designed living room" className="aspect-[4/3] w-full rounded-lg object-cover shadow-lift" />
  </section>
  <section className="bg-secondary py-16"><div className="container-site grid gap-5 md:grid-cols-4">{[[ShieldCheck,"Quality Properties","Carefully planned for quality, usability and lasting value."],[MapPin,"Prime Locations","Connected communities near the places daily life depends on."],[BadgeIndianRupee,"Transparent Pricing","Clear starting prices and straightforward conversations."],[Users,"Expert Assistance","One knowledgeable team supports your property journey."]].map(([I,t,d])=>{const Icon=I as typeof ShieldCheck;return <div key={t as string} className="rounded-lg bg-card p-6"><Icon className="size-7 text-brass"/><h2 className="mt-4 text-xl font-semibold">{t as string}</h2><p className="mt-2 text-sm text-muted-foreground">{d as string}</p></div>})}</div></section>
  <section className="container-site py-16 text-center"><h2 className="text-4xl font-semibold">Ready to find your new home?</h2><p className="mx-auto mt-3 max-w-xl text-muted-foreground">Explore our current properties or talk to a property expert.</p><div className="mt-7 flex justify-center gap-3"><Button asChild size="lg"><Link to="/properties">View Properties</Link></Button><Button asChild variant="outline" size="lg"><Link to="/contact">Contact Us</Link></Button></div></section>
</> }